# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: postgresql
  encoding: utf8
  database: morrowlate_development
  host: localhost
  pool: 5
  username: morrowlate
  password: "253648542"

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: morrowlate_test
  host: localhost
  pool: 5
  username: morrowlate
  password: "253648542"

production:
  adapter: postgresql
  encoding: utf8
  database: morrowlate_production
  pool: 5
  username: morrowlate
  password: "253648542"

cucumber:
  <<: *TEST
